import express from 'express';
import { randomBytes,randomUUID } from 'node:crypto';
import { analyzeSnippet,eventSchema,presentationSchema } from '../src/core.js';
import { widgets } from './store.js';
import { widgetRuntime } from './widget-runtime.js';
const app=express(); app.disable('x-powered-by'); app.use(express.json({limit:'110kb'}));
app.use((_req,res,next)=>{res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Referrer-Policy','strict-origin-when-cross-origin');next();});
app.post('/api/snippets/analyze',(req,res)=>{try{res.json(analyzeSnippet(String(req.body?.input||'')));}catch(e){res.status(400).json({error:e instanceof Error?e.message:'Unsupported snippet format'});}});
app.post('/api/widgets',(req,res)=>{try{const binding=analyzeSnippet(String(req.body?.source||''));const presentation=presentationSchema.parse(req.body?.presentation);const id=randomUUID();const widget={id,publicKey:randomBytes(16).toString('base64url'),name:String(req.body?.name||'Untitled widget').slice(0,80),status:'draft' as const,binding,presentation,launchMode:'modal' as const,version:0};widgets.set(id,widget);res.status(201).json(widget);}catch(e){res.status(400).json({error:e instanceof Error?e.message:'Invalid request'});}});
app.post('/api/widgets/:id/publish',(req,res)=>{const w=widgets.get(req.params.id);if(!w)return res.status(404).json({error:'Not found'});w.status='published';w.version++;res.json(w);});
app.get('/api/public/widgets/:key',(req,res)=>{const w=[...widgets.values()].find(x=>x.publicKey===req.params.key&&x.status==='published');if(!w)return res.status(404).json({error:'Widget unavailable'});res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Cache-Control','public,max-age=60,stale-while-revalidate=300');res.json({publicKey:w.publicKey,presentation:w.presentation,launchMode:w.launchMode,destinationUrl:w.binding.canonicalDestinationUrl,version:w.version});});
app.post('/api/public/events',(req,res)=>{const parsed=eventSchema.safeParse(req.body);if(!parsed.success)return res.status(400).json({error:'Invalid event'});res.status(202).json({accepted:true});});
app.get('/api/ehr/status',(_req,res)=>res.json({provider:'telehealthus',status:'Mock',message:'Local adapter data; live API needs configuration'}));
app.get('/api/ehr/clinics',(_req,res)=>res.json([{id:'28',name:'Desert Wellness',categories:[{id:'4',name:'Weight Loss',packages:[{id:'38',name:'Tirzepatide Monthly',price:399},{id:'37',name:'Semaglutide Monthly',price:249}]}]},{id:'82',name:"Modern Men's Health",categories:[{id:'9',name:'Vitality',packages:[{id:'91',name:'Core Vitality',price:189}]}]}]));
app.get('/api/health',(_req,res)=>res.json({status:'ok'}));
app.get('/embed/v1/widget.js',(_req,res)=>{res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Cache-Control','public,max-age=3600');res.type('application/javascript').send(widgetRuntime)});
app.listen(Number(process.env.PORT||4100),()=>console.log('TurnWidget API on http://localhost:'+(process.env.PORT||4100)));
